### PR TITLE
Add display manager switcher

### PR DESCRIPTION
**Pull request by vajdao**
Add display manager switcher (all DE, except Plasma)
Update base en translation
Update hu translation

### CODE REVIEW

**Comment by dolphinoracle** [comment]
why not plasma?

**Comment by dolphinoracle** [comment]
merged into new branch "display-manager" for now.   idea needs fleshed out.

**Comment by vajdao** [comment]
Plasma uses sddm, fluxbox and xfce uses lightdm. It was more straightforward for now to just simply do a dpkg-reconfigure lightdm within the code. I think it's possible to dynamically query the actual used dm  into a variable and use it for dpkg-reconfigure instead so it would apply to any DM. I did a couple of tests though, and it worked for plasma too. However I wasn’t satisfied with the code I wrote, since I was in a rush, so I decided to simplify it for now, but the idea is here if you want to use it. Feel free to modify it, and I'm happy I could contrib to the project, thanks for the merge to a new branch, it's a good start. When I'll have some more free time, I'll update the code, in case if no one else modified in the meantime 🙂

**Comment by dolphinoracle** [comment]
took your idea, and ran with it.

https://github.com/MX-Linux/mx-tweak/pull/155

current main "gtk3" branch has a display manager chooser on the "other" tab that will show if more than one display manager is present.  does use dpkg-reconfigure as you suggested, but does not rely on the proper configuration  (or presence) of a debconf graphical helper.   we preseed debconf with the choice we want, then run dpkg-reconfigure with the "noninteractive" DEBIAN_FRONTEND env. variable.

let me know what you think.  

thank thanks.

**Comment by vajdao** [comment]
You're very welcome @dolphinoracle, very nice idea and thanks for implementing this :) Glad I could help.

**Pull request merged**
